# An example of a trigger service.
# This can be used for testing but a semantically meaningful
# one should be created to be built upon.
sensor_msgs/Image rgb
sensor_msgs/Image depth
sensor_msgs/CameraInfo camera_info
---
bool success   # indicate successful run of triggered service
